[package]
name = "clap-link"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib"]


[dependencies]
wolfram-library-link = "0.2.8"
clap = { version = "4.1.6", features = ["string"] }
